=== oZep/CSI3140/assignment6_300219818__300235525/nutrition.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Define complex types -->
  <xs:complexType name="caloriesType">
    <xs:sequence>
      <xs:element name="total" type="xs:string"/>
      <xs:element name="fat" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fatType">
    <xs:sequence>
      <xs:element name="total" type="xs:string"/>
      <xs:element name="saturated" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="carbohydratesType">
    <xs:sequence>
      <xs:element name="total" type="xs:string"/>
      <xs:element name="fiber" type="xs:string"/>
      <xs:element name="sugars" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Define element structure -->
  <xs:element name="product">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="serving_size" type="xs:string"/>
        <xs:element name="calories" type="caloriesType"/>
        <xs:element name="fat" type="fatType"/>
        <xs:element name="cholesterol" type="xs:string"/>
        <xs:element name="sodium" type="xs:string"/>
        <xs:element name="carbohydrates" type="carbohydratesType"/>
        <xs:element name="protein" type="xs:string"/>
      </xs:sequence>
      <!-- Define attribute for product name -->
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== oZep/CSI3140/assignment6_300219818__300235525/nutrition.xml
<?xml version="1.0"?>

<product name = "Grandma White's Cookies"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="nutrition.xsd"
    >
    <serving_size>1 package</serving_size>
    <calories>
        <total>260 calories</total>
        <fat>100 calories</fat>
    </calories>
    <fat>
        <total>11 grams</total>
        <saturated>2 grams</saturated>
    </fat>
    <cholesterol>5 milligrams</cholesterol>
    <sodium>210 milligrams</sodium>
    <carbohydrates>
        <total>36 grams</total>
        <fiber>2 grams</fiber>
        <sugars>15 grams</sugars>
    </carbohydrates>
    <protein>5 grams</protein>
</product>
